#!/bin/php
<?php

/**
 * This program analyses saved playlists locally and print a report for each of them (artists, genres, etc.) 
 *
 * @package PS\ListeningData
 * @author Paul Schuhmacher
 */

require_once 'config.php';
require_once 'func.php';

if (!DEBUG_MODE) {
    set_exception_handler(function (Exception $e) {
        die($e->getMessage());
    });
}

$files = scandir(BACKUP_DIR);

//Seulement les fichiers . et ..
if (count($files) == 2) {
    echo "Réaliser un backup de vos playlists avant (avec le programme 'backup-playlists')";
    die;
}

if ($files == false) {
    printf("Impossible de lire le contenu du dossier %s. Le dossier %s n'existe peut-être pas. Réaliser un backup de vos playlists avant (avec le programme 'backup-playlists')\n", BACKUP_DIR, BACKUP_DIR);
    exit;
}

foreach ($files as $file) {

    if ($file === '.' || $file == '..' || pathinfo($file, PATHINFO_EXTENSION) != 'json')
        continue;

    printf("Playlist %s\n", pathinfo($file, PATHINFO_FILENAME));

    $path = sprintf("%s/%s", BACKUP_DIR, $file);

    $content = file_get_contents($path);

    if ($content == false) {
        echo "Impossible de lire le contenu du fichier %path. Playlist ignoré." . PHP_EOL;
        continue;
    }

    $tracks = json_decode($content);

    if ($tracks == null) {
        echo "Les données sur la playlist ne sont pas dans un format JSON valide. Playlist ignorée." . PHP_EOL;
        continue;
    }
    ddump($tracks);
}
