#!/bin/php
<?php

/**
 * This program analyses saved playlists locally and print a report for each of them (artists, genres, etc.) 
 * Report is printed on STDOUT for easy grep.
 *
 * @package PS\ListeningData
 * @author Paul Schuhmacher
 */

require_once 'config.php';
require_once 'func.php';

setlocale(LC_ALL, 'C.UTF-8');



if (!DEBUG_MODE) {
    set_exception_handler(function (Exception $e) {
        die($e->getMessage());
    });
}

$files = scandir(BACKUP_DIR);

//Seulement les fichiers . et ..
if (count($files) == 2) {
    echo "Réaliser un backup de vos playlists avant (avec le programme 'backup-playlists')";
    die;
}

if ($files == false) {
    printf("Impossible de lire le contenu du dossier %s. Le dossier %s n'existe peut-être pas. Réaliser un backup de vos playlists avant (avec le programme 'backup-playlists')\n", BACKUP_DIR, BACKUP_DIR);
    exit;
}

//Loop over playlists
foreach ($files as $file) {

    if ($file === '.' || $file == '..' || pathinfo($file, PATHINFO_EXTENSION) != 'json')
        continue;

    $playlist_name = pathinfo($file, PATHINFO_FILENAME);


    $path = sprintf("%s/%s", BACKUP_DIR, $file);

    $content = file_get_contents($path);

    if ($content == false) {
        echo "Impossible de lire le contenu du fichier %path. Playlist ignoré." . PHP_EOL;
        continue;
    }

    $items = json_decode($content);

    if ($items == null) {
        echo "Les données sur la playlist ne sont pas dans un format JSON valide. Playlist ignorée." . PHP_EOL;
        continue;
    }

    //Reorganize tracks/artist
    $result = [];

    foreach ($items as $item) {

        if (!isset($item->track)) {
            continue;
        }

        $artists = $item->track->artists;

        foreach ($artists as $artist) {
            $result[$artist->name][] = $item->track->name;
        }
    }

    $nb_of_tracks = count($items);

    printf("* Playlist $playlist_name (%d tracks, %d artists)\n", $nb_of_tracks, count($result));

    //Sort by artists with higher number of tracks (desc)
    uasort($result, function ($a, $b) {
        if (count($a) == count($b))
            return 0;
        return count($a) < count($b) ? 1 : -1;
    });

    foreach ($result as $artist_name => $tracks) {
        $frac = count($tracks) / $nb_of_tracks;
        if ($frac >= 0.015) {
            $width = 40;
            $pad = $width - mb_strwidth($artist_name, 'UTF-8');
            printf(" %s (%2d)%s (playlist: %s) (%3.0f%%) %s\n", $artist_name, count($tracks), str_repeat(' ', max(0, $pad)), $playlist_name,  $frac * 100,  ascii_bar($frac));
        }
    }

    printf("\n");
}
