#!/bin/php
<?php

/**
 * This program queries Spotify to backup user playlists.
 * This backup will allow importing all this data (notably playlists) into another account or service later.
 *
 * @package PS\ListeningData
 * @author Paul Schuhmacher
 */

require_once 'config.php';
require_once 'func.php';

if (!DEBUG_MODE) {
    set_exception_handler(function (Exception $e) {
        die($e->getMessage());
    });
}

$access_token = connect();

$me = request('/me', $access_token);

if (!isset($me['id'])) {
    exit("Aucun identifiant de compte utilisateur obtenu. Réessayer.");
}

define('CURRENT_USER_ID', $me['id']);

printf("Account: %s (id: %s)\n", $me['display_name'], CURRENT_USER_ID);

backup_playlists($access_token, CURRENT_USER_ID, 'OWNED_ONLY');
